### ISSUE TITLE
encode error  red color  change to blue

### ISSUE THREAD

**Issue by bunnyblue** [alexey-pelykh/webp-android-backport#4]
![kele](https://cloud.githubusercontent.com/assets/1221755/2751783/bd37478e-c8eb-11e3-8438-7a0920e64aa1.jpg)
  this  image  encode error

**Comment by bunnyblue** [comment]
when  encode this jpg to webp,red color look like blue.

**Comment by alexey-pelykh** [comment]
Hi, finally I have time for this issue. What device do you use?

**Comment by alexey-pelykh** [comment]
Anyways, fixed.
