### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION

### ISSUE THREAD

**Issue by ongakuer** [alexey-pelykh/webp-android-backport#6]
Great Library！
I try to decode webp file in Android 4.0+  (so I can use latest cwebp). But crashed on some devices.

```
JNI DETECTED ERROR IN APPLICATION: jclass is an invalid local reference: 0x100015 (0xdead4321) 
in call to GetStaticObjectField 
```  

I think this is the reason. http://android-developers.blogspot.com/2011/11/jni-local-reference-changes-in-ics.html

**Comment by alexey-pelykh** [comment]
Thanks to @wyouflf that created pull request #8 this should be fixed.
