### ISSUE TITLE
ndk cannot complie 

### ISSUE THREAD

**Issue by leonzhuhi** [alexey-pelykh/webp-android-backport#7]
[armeabi] Compile++ thumb: webpbackport <= android_backport_webp.cpp
[armeabi-v7a] Compile++ thumb: webpbackport <= android_backport_webp_WebPFactory.cpp
jni/webpbackport/android_backport_webp_WebPFactory.cpp:8:25: fatal error: webp/decode.h: No such file or directory
compilation terminated.                                   
make.exe: *** [obj/local/armeabi-v7a/objs/webpbackport/android_backport_webp_WebPFactory.o] Error 1
make.exe: *** Waiting for unfinished jobs....

**Comment by addynj** [comment]
some error

**Comment by MaisonWan** [comment]
webp/decode.h is missing

**Comment by zmzing** [comment]
yes, same error

jni/webpbackport/android_backport_webp_WebPFactory.cpp:8:25: fatal error: webp/decode.h: No such file or directory

**Comment by alexey-pelykh** [comment]
Have you initialized GIT submodules?

**Comment by alexey-pelykh** [comment]
Just checked - probably you haven't initialized git submobule
