### ISSUE TITLE
error when building with android studio

### ISSUE THREAD

**Issue by ravithejamaddineni** [alexey-pelykh/webp-android-backport#9]
jni/webpbackport/android_backport_webp_WebPFactory.cpp:8:25: fatal error: webp/decode.h: No such file or directory
 #include <webp/decode.h>
                         ^
compilation terminated.
make: *** [obj/local/arm64-v8a/objs/webpbackport/android_backport_webp_WebPFactory.o] Error 1
make: *** Waiting for unfinished jobs....
jni/webpbackport/android_backport_webp_WebPFactory.cpp:8:25: fatal error: webp/decode.h: No such file or directory
 #include <webp/decode.h>
                         ^
compilation terminated.
make: *** [obj/local/mips64/objs/webpbackport/android_backport_webp_WebPFactory.o] Error 1
jni/webpbackport/android_backport_webp_WebPFactory.cpp:8:25: fatal error: webp/decode.h: No such file or directory
 #include <webp/decode.h>
                         ^
compilation terminated.
make: *** [obj/local/x86_64/objs/webpbackport/android_backport_webp_WebPFactory.o] Error 1
jni/webpbackport/android_backport_webp_WebPFactory.cpp:8:25: fatal error: webp/decode.h: No such file or directory
 #include <webp/decode.h>
                         ^
compilation terminated.
jni/webpbackport/android_backport_webp_WebPFactory.cpp:8:25: fatal error: webp/decode.h: No such file or directory
 #include <webp/decode.h>
                         ^
compilation terminated.
make: *** [obj/local/armeabi-v7a/objs/webpbackport/android_backport_webp_WebPFactory.o] Error 1
make: *** [obj/local/armeabi/objs/webpbackport/android_backport_webp_WebPFactory.o] Error 1
jni/webpbackport/android_backport_webp_WebPFactory.cpp:8:25: fatal error: webp/decode.h: No such file or directory
 #include <webp/decode.h>
                         ^
compilation terminated.
make: *** [obj/local/x86/objs/webpbackport/android_backport_webp_WebPFactory.o] Error 1
jni/webpbackport/android_backport_webp_WebPFactory.cpp:8:25: fatal error: webp/decode.h: No such file or directory
 #include <webp/decode.h>
                         ^
compilation terminated.
make: *** [obj/local/mips/objs/webpbackport/android_backport_webp_WebPFactory.o] Error 1
:webp-android-backport-library:buildNative FAILED
Error:Execution failed for task ':webp-android-backport-library:buildNative'.
> Process 'command 'sh'' finished with non-zero exit value 2
Information:BUILD FAILED

**Comment by alexey-pelykh** [comment]
Have you initialized git submodules properly?

**Comment by ravithejamaddineni** [comment]
I have downloaded the entire project as zip and imported in Android studio 2.0

**Comment by alexey-pelykh** [comment]
https://github.com/alexey-pelykh/webp-android-backport/blob/master/.gitmodules
https://git-scm.com/book/en/v2/Git-Tools-Submodules#Cloning-a-Project-with-Submodules

**Comment by ravithejamaddineni** [comment]
Thanks
